### PR TITLE
Small code optmizations.

### PR DESCRIPTION
**Pull request by brunao05**

### CODE REVIEW

**Comment by proudmonkey** [comment]
Thank you for the suggestion. I appreciate it. :)

I noticed that you replace string with vars. Vars shouldn't be overused for simple types and if you value readability. :)

**Comment by brunao05** [comment]
Done.

**Comment by proudmonkey** [comment]
@brunao05 Merged your changes. Thank you.

Can you please email me your full name and blog site so I can include you in the contributor list? Thanks!

**Comment by brunao05** [comment]
Sure thing

**Comment by proudmonkey** [comment]
Cool!
If you don't mind, can you star the repo to show support. :) 

Send your name and blog link if you have here: vmsdurano at gmail dot com. Thanks!

**Pull request merged**
